# Generated by Django 4.2.7 on 2023-11-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_nickname_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
