# Generated by Django 4.2.7 on 2023-11-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_firs_name_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
