# Generated by Django 4.2.7 on 2023-11-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
