name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.10.6]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        env:
          SECRET_KEY: secret_key
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        env:
          SECRET_KEY: secret_key
        run: |
          pip install poetry
          make build
          poetry run python manage.py migrate
      - name: Run linter and tests
        env:
          SECRET_KEY: secret_key
        run: |
          make lint
          make tests
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        env:
          SECRET_KEY: secret_key
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand:
            make coverage
            make report
          debug: true
